#!/usr/bin/env php
<?php

/** @var \Composer\Autoload\ClassLoader $loader */
$loader = include __DIR__ . '/../vendor/autoload.php';
require_once __DIR__ . '/AppKernel.php';

use Symfony\Component\Console\Input\ArgvInput;
use Kyoya\PhpJobRunner\Command\Application;

$input = new ArgvInput();
$env   = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'dev');
$debug = getenv('SYMFONY_DEBUG') !== '0' && $env !== 'prod';

$kernel      = new AppKernel($env, $debug);
$application = new Application($kernel);
$application->run($input);
